name: Build Librespot

on:
  push:
    branches:
    - master

jobs:
  librespot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Nix package manager
        uses: cachix/install-nix-action@v14
      - name: Build librespot
        run: |
          nix-build
          mkdir -p build
          cp -L ./result/* ./build/
      - name: Get version tag
        id: version
        run: |
          echo "::set-output name=version::$(cat ./build/version.txt)"
      - name: Upload artifacts to GitHub releases
        uses: softprops/action-gh-release@v1
        with:
          files: './build/*'
          name: v${{ steps.version.outputs.version }}
          tag_name: v${{ steps.version.outputs.version }}
          body: "Release Librespot v${{ steps.version.outputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
